name: curso_data_eng
version: '1.0.0'
config-version: 2

profile: default

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  curso_data_eng:

    staging:
      +database: DE56_DEV_SILVER_DB
      +schema: staging
      +materialized: view

    marts:
      +database: DE56_DEV_GOLD_DB
      +schema: marts
      +materialized: table

vars:
  budget_date: '2024-01-01'
